using System;
using System.Diagnostics;

namespace VowelsSubstring
{
    class Program
    {
        static void Main(string[] args)
        {
            /*Avem un string si trebuie sa gasim substringul de o anumita dimensiune, care are cele mai multe vocale. Stringul si dimensiunea sunt date de intrare.

            Ex: 
            String = “eu ce mananc azi si de unde, ca n-am cu cine face comanda de grup”
            Dimensiune = 4
            Raspuns = “eu c”

            String=”cooperant”
            Dimensiune=4
            Raspuns=”oope” – substringul cu cele mai multe vocale(3) este “oope”

            String=”bnmmnbfhgjk”
            Dimensiune=2
            Raspuns=”Not found” – nu contine nicio vocala
            */

            var text = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at tempor dolor. Vestibulum maximus posuere ipsum. Quisque pellentesque quam a lacus egestas, id porttitor elit viverra. Sed dignissim mauris sed semper accumsan. Maecenas accumsan tincidunt nunc, ut sodales dui dapibus in. Vivamus quis fermentum mi. Etiam sit amet velit sodales, finibus est at, pellentesque massa.

Nulla eget arcu sit amet turpis iaculis ultricies in id enim. Quisque vitae ipsum non orci blandit ultricies vitae sit amet neque. Pellentesque gravida luctus arcu, id ultrices nunc tristique nec. Nulla at neque arcu. Mauris dignissim at neque vel consequat. Nulla ultricies nisl in turpis ultrices consectetur. Phasellus cursus posuere lacus in tempus. Cras nulla arcu, rutrum et dolor ut, pulvinar tristique odio. Morbi felis eros, gravida eget pellentesque non, porta id quam. Maecenas luctus, tellus ut eleifend tempor, lectus risus pretium purus, ac semper velit nibh nec urna. Donec porttitor odio in leo posuere, vitae bibendum sapien auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

In et ligula quis quam blandit laoreet. Cras tincidunt dui aliquet rhoncus tempus. Integer convallis enim nec lacus tincidunt hendrerit nec non ante. Duis et enim fermentum, pulvinar purus luctus, fermentum ante. In mattis nisl a pharetra posuere. In vitae nisi et est congue condimentum a sed lorem. Phasellus ut eros ut purus rutrum egestas eget vitae est. Sed sodales venenatis cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum leo id turpis tempor scelerisque. Aenean tristique interdum quam ut lacinia. Morbi eget sodales tortor. Nulla mattis, eros et placerat tincidunt, nisl dolor condimentum enim, non suscipit erat tellus eget leo. Nam vel condimentum quam. Praesent ac erat leo. In vulputate, mauris porta pulvinar tempus, nisl purus accumsan velit, vel eleifend elit orci ut nisi.

Maecenas ut libero consectetur, dapibus velit eu, tristique ipsum. In enim felis, rutrum suscipit mauris ac, pretium vehicula dui. Integer et augue accumsan, vulputate nisi sed, auctor turpis. Nullam eleifend euismod lacus, ut rhoncus metus egestas ut. In fringilla aliquet orci vel mattis. Aliquam erat volutpat. Morbi elementum non purus in suscipit. Nulla elementum euismod leo vitae tincidunt. Etiam sagittis sapien convallis, iaculis dolor vel, ornare elit. Nam sed mauris in orci molestie ultricies vel ut urna. Proin metus neque, viverra auctor tellus et, finibus faucibus risus. Nulla efficitur interdum urna. Pellentesque semper leo iaculis, dictum mauris et, pretium lacus. Vestibulum metus turpis, laoreet et vulputate in, aliquam eget ex. Integer laoreet massa ipsum, non sagittis ante elementum nec. Sed sit amet fringilla nisi.

Morbi consectetur urna dapibus purus semper semper. Donec pulvinar justo in odio ultricies facilisis eget at libero. Mauris vulputate consequat feugiat. Cras vitae fermentum dui. Nam placerat quis nisi non tincidunt. Nullam sit amet pulvinar nunc. Nullam ullamcorper sollicitudin facilisis. Morbi varius interdum augue. Nunc sit amet nibh a mi congue consequat. Aliquam porttitor porta ornare. Integer in odio ac velit tincidunt interdum. Vestibulum tristique, nisi non luctus blandit, massa risus lacinia nunc, sit amet blandit ipsum sem eget ipsum. Maecenas interdum, odio nec suscipit interdum, erat arcu euismod ligula, ut auctor lorem enim eget diam. Ut aliquam et ex eget finibus. Sed nec metus id ligula sollicitudin feugiat et a nisi. Vivamus in fermentum erat.

Vivamus id sem nisl. Phasellus gravida turpis tortor, malesuada elementum enim luctus nec. Duis ac neque urna. Integer sapien mi, lobortis convallis mollis a, porttitor eget lectus. Pellentesque a bibendum libero. Donec pellentesque facilisis blandit. Nunc tincidunt nibh ut risus vulputate, sit amet elementum nulla malesuada. Proin interdum, lectus sed eleifend vulputate, arcu tortor ornare felis, quis accumsan eros ligula sed dolor. Morbi laoreet tortor arcu. Nulla ullamcorper ipsum id odio sodales convallis.

Proin a diam non eros tempor mollis. Integer at tellus porttitor, mollis nunc suscipit, fringilla metus. Nulla facilisi. Mauris vel nulla enim. Aliquam malesuada vehicula gravida. Nulla tempor sed elit vitae rhoncus. Nullam pulvinar commodo pharetra. Suspendisse malesuada felis vitae malesuada rutrum. Etiam placerat leo id sollicitudin gravida. Sed semper faucibus nisi pellentesque maximus. Donec congue a mi at vulputate. Vestibulum id orci diam. Nullam consequat at mi sit amet maximus. Pellentesque tincidunt sollicitudin ipsum, non vulputate eros accumsan sed.

Nam gravida elementum consequat. Donec id elementum ex, vel commodo risus. Praesent id odio enim. Nam eu dolor sit amet ligula sollicitudin ultricies. Nunc sagittis sed sapien et sodales. Pellentesque hendrerit mauris sed purus tincidunt, convallis interdum lectus accumsan. Nunc tincidunt suscipit risus eu pharetra.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut posuere purus ut enim fringilla, ac lobortis tortor consequat. Morbi volutpat sagittis arcu consectetur scelerisque. Etiam tincidunt, justo a bibendum posuere, turpis libero ornare sapien, at vestibulum est diam quis ipsum. Cras maximus, sapien sit amet aliquam porta, diam quam ultricies mauris, in lacinia turpis leo a quam. Quisque elementum tellus tincidunt, venenatis dui eu, mattis lorem. Donec varius tortor eget est suscipit tempus. Morbi dapibus massa ut ultrices lobortis. Nullam sit amet faucibus quam, et sagittis est. Etiam congue varius metus in finibus.

Aliquam pulvinar rutrum mauris, ut pretium urna. Vestibulum gravida lorem vel fermentum scelerisque. Sed sapien justo, ultrices sit amet nunc eget, finibus dapibus urna. Vivamus elit arcu, porttitor eu tellus ac, sollicitudin consectetur justo. Duis pulvinar, lacus non ullamcorper ornare, sapien erat viverra odio, quis vehicula nunc tortor vitae libero. Praesent id magna sed arcu elementum hendrerit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ac felis vel dui iaculis imperdiet id non dolor. Aliquam mauris turpis, varius vitae porta tempus, congue vitae nisi. Sed interdum vehicula diam sed interdum. Praesent malesuada, leo vel congue accumsan, dolor erat convallis mi, ac tempus sapien eros sed quam. Morbi elit augue, posuere a consectetur condimentum, accumsan eu elit. Vestibulum quis leo ac risus accumsan volutpat venenatis eu dolor. Etiam quam odio, luctus ac enim quis, porta fringilla lacus. Phasellus sollicitudin ipsum quis eros auctor, in vestibulum turpis consequat. Quisque bibendum porttitor justo, quis suscipit lorem lacinia eu.

Maecenas et neque lectus. Donec lobortis eros sed hendrerit tincidunt. Sed sapien neque, commodo vel leo non, facilisis malesuada dui. Pellentesque suscipit suscipit felis at commodo. Vivamus a ornare magna, at finibus tellus. Integer maximus molestie fermentum. Vestibulum vitae viverra arcu. Aenean sed felis felis. In rhoncus sodales libero. Sed sodales auctor ante, at semper odio tempor eget. Phasellus sed malesuada quam, nec commodo quam. Proin ornare posuere urna quis luctus. Nam in lacus nec elit varius sollicitudin a facilisis ex. Maecenas sed velit at nisl eleifend dignissim eu vitae ante.

Mauris sollicitudin pharetra sem eget placerat. Sed turpis neque, dignissim faucibus varius vitae, mollis vitae turpis. Praesent in neque vulputate, dignissim lorem sed, mollis ipsum. Integer fermentum nisi sit amet sem faucibus, et bibendum quam molestie. Nulla vitae pharetra purus, nec scelerisque velit. Donec finibus enim vel sodales venenatis. Praesent sagittis nec quam ut molestie. Duis dignissim leo at lectus gravida, in consectetur dolor pulvinar.

Nam ornare neque erat, ut interdum metus pharetra sit amet. Nunc placerat ante nec bibendum rhoncus. Maecenas facilisis lectus ut pharetra fermentum. Suspendisse potenti. Pellentesque rutrum a nisl sed dictum. Nullam ut nisl interdum erat aliquam ultrices sed at neque. Quisque vel mi quis nisi convallis luctus non nec mi. Curabitur mollis est sit amet pretium maximus. Vestibulum ac luctus massa. Duis eget lacus dignissim arcu posuere ultrices. Phasellus vel luctus arcu. Phasellus quis ultrices augue. Suspendisse sit amet luctus est, non fermentum tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tincidunt finibus urna, at vulputate velit semper eget.

Etiam efficitur tortor quis eros dictum pellentesque. Integer vitae eleifend ex. Etiam id interdum odio, a sollicitudin turpis. Aenean luctus quam elit, ut tincidunt enim mollis nec. Ut lectus arcu, faucibus a vestibulum nec, laoreet vel nisl. Nullam viverra nisl metus, ac semper sem ullamcorper sed. Vivamus placerat ullamcorper elit pulvinar faucibus. Mauris id metus nec nibh sagittis mattis. Vestibulum mattis enim sapien, ut viverra neque pharetra id. Donec ut malesuada quam.

Donec id iaculis dolor, eget tempor quam. Aliquam sollicitudin ac risus suscipit volutpat. Pellentesque sit amet consequat sapien. Vivamus lectus orci, efficitur sed ultrices at, feugiat eget neque. Fusce ullamcorper imperdiet diam, tincidunt hendrerit purus tristique at. Suspendisse ultrices lobortis turpis, vel gravida metus convallis nec. Donec molestie, urna quis euismod ornare, lacus ante posuere velit, in fringilla enim tortor vel nulla. Sed interdum leo in diam imperdiet, a vehicula nisl tempus. Phasellus non condimentum augue, nec vehicula tellus. Mauris pellentesque nisl at lobortis condimentum. Aliquam quis magna diam. Vivamus porta gravida mauris.

Nunc in ornare turpis, id eleifend quam. Aenean dictum eget tortor eget pulvinar. Sed vitae mattis lorem. Maecenas nec gravida mi. Nulla imperdiet mauris et porttitor iaculis. Sed condimentum tortor ac libero mattis vehicula. Integer feugiat justo in leo interdum porta. Donec ac blandit eros, vitae lacinia felis. Aliquam elementum elit non aliquam consectetur. Duis venenatis cursus nibh vitae blandit. Morbi pretium lacus erat, sed porta eros mattis nec. Aliquam tellus ex, pretium eu aliquam at, sollicitudin non leo. Cras commodo ultricies ante, eget tristique sapien. Aenean sed convallis dolor, faucibus fermentum sapien.

Ut auctor ante sit amet rutrum condimentum. Ut ante libero, volutpat at suscipit vitae, sodales quis lectus. Vestibulum nec eleifend leo, non consequat lorem. In congue magna eget porttitor vehicula. Etiam ut sagittis augue, id cursus felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus porttitor auctor volutpat. Morbi libero nisi, lacinia sed rhoncus quis, luctus non quam. Etiam dapibus laoreet diam, sed venenatis libero. Duis sollicitudin ex et consectetur lobortis. Ut sed tincidunt enim. Etiam luctus fringilla justo, vel semper lacus interdum ac. Duis nec felis a odio tincidunt imperdiet.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi ac vehicula enim. Suspendisse potenti. Vestibulum sed egestas mi. Aliquam lectus neque, ultricies quis orci vel, tempor rhoncus orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam quis sem luctus, auctor dui vitae, imperdiet enim. Phasellus at est vel massa imperdiet aliquam. Nam fermentum pulvinar mauris sit amet euismod.

Nam euismod imperdiet risus, sed volutpat nunc porta vel. Praesent at porta felis. Sed mattis, magna non luctus sollicitudin, libero justo tempus metus, et facilisis sapien ipsum a sapien. Cras vitae odio lacus. Sed vitae fringilla justo. Nam libero nunc, viverra in volutpat quis, lobortis at est. Cras suscipit convallis nulla nec bibendum. Nullam ac ante sed ligula ultrices consectetur non et mi. Nullam ut est elementum purus consectetur molestie.

Proin dignissim magna ut diam dignissim cursus. Donec quis volutpat magna, vel ullamcorper ante. In sodales, odio vitae auctor rutrum, nibh massa scelerisque eros, quis pellentesque nibh massa ut ante. Aenean pulvinar velit at tincidunt faucibus. Quisque tincidunt orci sed nibh mollis lacinia. Curabitur turpis turpis, gravida et tincidunt a, lacinia sit amet elit. Sed tincidunt pretium augue, id condimentum lacus. In aliquam ante ut mauris maximus, eget placerat nisl pulvinar. Sed semper tellus ac pretium sollicitudin. Aliquam eget imperdiet tellus. Proin suscipit risus eget quam pulvinar, sit amet aliquam nulla cursus.

Integer dolor enim, vehicula a commodo eu, euismod et purus. Sed eget congue urna. Sed in est sit amet felis tristique pretium. Fusce non risus dictum, euismod turpis eu, consequat tellus. Suspendisse a velit fermentum, efficitur augue in, scelerisque mi. Etiam id aliquet sem. Aliquam blandit ultricies nunc non consequat. Curabitur viverra urna vitae lobortis tincidunt. Vivamus scelerisque ullamcorper turpis bibendum gravida. Pellentesque nulla augue, consectetur placerat consectetur quis, feugiat quis elit. Sed non ultricies felis. In hac habitasse platea dictumst. Fusce non auctor arcu. Cras eget posuere turpis.

Proin dignissim id felis sit amet consectetur. Phasellus ut ipsum sed magna imperdiet posuere eget in neque. Aliquam rutrum lacinia sem vel condimentum. Praesent pulvinar mauris a libero consectetur dignissim quis a est. Sed in lectus at nisl sagittis consequat. Sed sapien neque, tincidunt ut erat tempor, congue elementum arcu. Morbi a tincidunt odio, sit amet feugiat lectus. Donec finibus tortor vitae felis convallis consequat. Sed dignissim eu tortor sed gravida. Integer vel erat et dolor tincidunt convallis. Nullam orci augue, tincidunt nec imperdiet eu, congue eget ipsum. Phasellus quam nibh, suscipit eget ullamcorper in, tincidunt a tellus. Duis finibus libero et commodo varius. Suspendisse potenti.

Aenean blandit leo sed massa vestibulum, ac gravida augue iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ut fringilla nulla. Etiam pharetra mi ante, vel cursus enim euismod at. Nullam sed orci mi. Morbi molestie ipsum felis, vitae lobortis quam laoreet id. Nam sed scelerisque orci, rhoncus lacinia sem. Aliquam erat volutpat. Nullam felis libero, vulputate sit amet euismod ac, viverra a leo. Nam sit amet lorem convallis, viverra justo ac, tristique urna. Sed a eleifend purus. Morbi non viverra sem, a imperdiet tortor. Donec eget consectetur metus, in molestie risus. Sed luctus cursus urna in vulputate. Integer quis dapibus sapien.

In vitae tempor leo. Integer et purus sit amet diam consectetur blandit a tincidunt arcu. Nullam vitae sem justo. Quisque est eros, varius in tincidunt id, euismod ut erat. Sed quis risus in mauris accumsan vehicula. Sed ut sapien vel diam euismod dictum id vel odio. Maecenas ultricies feugiat sagittis. Vivamus leo quam, bibendum eu mollis ut, tempus in justo. Fusce quam ligula, vulputate tristique dui vitae, accumsan volutpat urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. In fringilla elit ac dolor sagittis malesuada non ac nulla. Mauris sed hendrerit felis. Nulla semper sagittis pulvinar. Donec sit amet efficitur purus. Suspendisse tristique tortor vel faucibus iaculis. Nam nec quam pulvinar, varius metus laoreet, fermentum leo.

Nunc consequat eu sem id tristique. Sed interdum luctus vehicula. Maecenas enim urna, porta et auctor nec, venenatis sed ex. Sed vestibulum, ligula vitae tempor efficitur, urna ex scelerisque nisi, quis pharetra augue lectus eget lectus. Morbi in nibh bibendum, molestie massa id, feugiat ligula. Duis ipsum augue, feugiat sollicitudin ligula sed, congue posuere risus. Proin lobortis, diam eu congue blandit, diam risus egestas libero, ac commodo eros mi at dolor. Phasellus varius leo eget mauris ullamcorper, et laoreet ex accumsan. Mauris vel tortor semper, imperdiet metus vel, pretium nulla. Sed in lacus ornare, pulvinar felis et, consectetur elit. Vivamus felis sem, ultricies in mi et, aliquam auctor erat. Sed et lectus ipsum. Quisque fringilla, enim vitae ornare blandit, purus enim pulvinar ligula, sit amet accumsan risus ex eget nibh. Morbi vel facilisis erat. Nunc suscipit libero id blandit cursus.

Sed tempus non tortor sit amet venenatis. Nullam interdum a metus non aliquam. Donec interdum nisi eu dolor vestibulum tristique. Vestibulum sed diam dignissim enim cursus tempor a ac erat. Fusce pellentesque porttitor elementum. Aenean vitae nibh ut est lobortis viverra bibendum eu neque. Praesent id dolor non nisi scelerisque bibendum. Ut nisl libero, imperdiet sed nibh quis, ultrices faucibus nulla. Nullam et turpis scelerisque risus suscipit aliquet interdum sit amet risus. Etiam bibendum sodales vestibulum. Nunc et elit eget orci sollicitudin dapibus. Vivamus nec aliquet felis, in rhoncus ante. Nunc odio velit, gravida ultrices mauris id, ultricies sollicitudin libero. Quisque placerat elit ut mauris egestas aliquam. Quisque neque turpis, finibus eget tincidunt sed, fermentum ac nibh. Donec sollicitudin suscipit tortor, a facilisis risus blandit et.

In rhoncus nec urna in luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur fermentum sagittis elit, quis congue erat mollis ut. Nam quis quam tellus. Sed dictum tristique eros, et finibus erat porttitor vel. Nunc magna massa, ornare nec nisi non, vulputate auctor sapien. Sed facilisis ex eu velit finibus, ut cursus dui finibus. Ut sed posuere tortor. Sed neque justo, viverra in vulputate eget, scelerisque eget velit.

Aenean quis augue ligula. Curabitur ut lobortis dui. Morbi sit amet dignissim leo. Aliquam molestie dolor ac nunc dictum, malesuada laoreet massa aliquet. Quisque placerat pharetra mauris, ac varius dui iaculis at. Curabitur cursus nisi ligula. Ut vitae rhoncus eros. Pellentesque rhoncus dolor in orci ullamcorper dictum. Quisque id sem est. Proin sem velit, scelerisque quis dictum vel, aliquet nec nibh. In lorem dui, volutpat eu erat sed, tempor scelerisque lacus. Duis laoreet dui eget metus auctor, et iaculis tortor bibendum. Praesent et sodales tellus. Praesent in vulputate turpis, eget semper dolor. Curabitur sodales interdum odio, malesuada facilisis tortor fermentum quis.

Mauris dapibus id libero ut bibendum. Suspendisse non egestas sapien. In hac habitasse platea dictumst. In suscipit magna ex, ut pulvinar nisi suscipit non. Quisque ut gravida ligula. Etiam a dignissim risus. Nunc consectetur congue purus, pretium elementum sem molestie at. Donec eu quam et sem venenatis pharetra at at enim. Cras vitae nulla ut nisl euismod dignissim vestibulum id turpis. Aenean molestie purus in orci consequat dignissim. Etiam sed libero nisi. Nunc turpis augue, iaculis sit amet augue malesuada, lacinia mollis purus. Sed lacus orci, sollicitudin elementum condimentum non, eleifend ut dui.

Duis nec diam non risus tincidunt ultrices. Praesent a nibh eget lacus iaculis bibendum. Cras vulputate, nibh ac ornare ullamcorper, risus leo tincidunt dolor, vel vehicula nibh velit quis ipsum. Praesent quis lectus et velit pulvinar suscipit vel at dolor. Suspendisse potenti. Nunc scelerisque hendrerit mauris, at porttitor libero suscipit ac. Nunc vel ultrices nulla, sed blandit nulla. Etiam pharetra varius risus a ultricies. Nullam dapibus sem vel nisi sagittis pellentesque. Proin sodales ipsum non lectus tincidunt efficitur. In id rhoncus felis. Suspendisse commodo tristique elit.

Mauris in ante vel nisl venenatis venenatis. Quisque tincidunt vitae eros non consequat. Aenean non volutpat augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec eleifend mauris ut tortor porttitor, non mattis lacus fringilla. Donec ornare nisl sit amet dui suscipit hendrerit. Nam at orci ac nunc dictum aliquam et vitae diam. Pellentesque nec odio augue. Suspendisse lectus lorem, placerat et nunc eu, commodo efficitur mauris. In et euismod nisi. Quisque in eleifend quam, vitae rutrum lectus. Proin bibendum nulla dui, vel maximus erat feugiat nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur tempus consequat ipsum non porttitor. Fusce id orci vestibulum mi rhoncus tempor.

Integer vitae tellus massa. Curabitur tristique feugiat ex, et euismod mauris ullamcorper vel. Suspendisse convallis ac mi et interdum. In pulvinar vitae lacus quis iaculis. Suspendisse sed diam eget lectus finibus lobortis sed in felis. Donec tortor nisl, facilisis a condimentum id, tempus sit amet lorem. Proin urna orci, fermentum quis urna eget, varius viverra nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Vivamus accumsan rhoncus lacinia. Pellentesque sed ligula varius, cursus orci ac, commodo nulla. Aenean ut elit vel tortor placerat varius. Proin nec aliquam felis. Suspendisse aliquam dolor nulla, eu ultricies mauris sodales vel. Nulla at nisl ut metus elementum lacinia. Vestibulum eu dolor ut risus convallis suscipit ac at nunc. Proin eget gravida urna. Ut pellentesque est ante, vitae placerat sapien convallis euismod. Phasellus ut nulla odio.

In fringilla justo quis tellus lacinia consectetur. Curabitur blandit iaculis nulla, id vestibulum tellus porta eget. Donec eleifend condimentum risus, non convallis nibh vehicula tincidunt. Ut finibus fermentum pulvinar. Integer quis elementum purus. Proin congue est elit, nec porttitor sem tempus eget. Nullam luctus finibus nisl, id imperdiet mi consequat quis.

Donec aliquet feugiat scelerisque. Duis nec enim vulputate, dignissim tellus congue, semper erat. Vestibulum dignissim pretium malesuada. Fusce vehicula augue ac arcu rutrum sagittis. Pellentesque gravida augue nec felis semper, non ultricies diam blandit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam eu nisl nulla. Ut iaculis ligula sed scelerisque tempor. Integer accumsan nisi et rhoncus vulputate. Ut id elementum nunc. Quisque efficitur odio in pellentesque cursus. Duis finibus massa sit amet lacus efficitur porta. Ut nec tellus ligula. Vestibulum aliquet justo id ex tempor pellentesque. Curabitur varius, ligula vel ullamcorper mattis, arcu est maximus libero, non vestibulum velit velit sed mi.

Curabitur maximus sagittis imperdiet. Suspendisse sollicitudin posuere mauris, eget lobortis odio. Maecenas tristique ante sapien, et feugiat nulla interdum a. Nam et est ut nibh feugiat accumsan ut vel justo. Curabitur at metus vel lorem tristique ornare. Nullam a nisi fermentum, commodo sem vitae, ornare ligula. Aenean bibendum, urna eget tempus euismod, tortor velit fermentum metus, non maximus nisi magna eu metus.

In vestibulum lacus ipsum, ut auctor ex sagittis non. Etiam lobortis, nibh eget faucibus volutpat, magna lacus consequat nulla, sed pellentesque magna purus in mauris. Fusce et aliquam nibh. Donec et facilisis ex. Sed at eros tellus. Praesent semper magna at condimentum pulvinar. Suspendisse potenti. Mauris elit felis, ultrices id blandit ut, elementum vel sapien. Nam scelerisque laoreet ex, lacinia ornare felis.

Aenean pulvinar mauris nec aliquet scelerisque. Ut hendrerit ex tellus, eu tincidunt lacus sollicitudin a. Phasellus sed ante risus. Aenean diam nulla, malesuada non sagittis vitae, sagittis vel lectus. Cras lobortis, velit vitae convallis tincidunt, nulla velit vehicula dui, in elementum libero risus non nisi. Pellentesque lacinia, libero eget lacinia mattis, nunc neque suscipit metus, non rutrum libero quam in ligula. Nunc sit amet felis iaculis magna faucibus molestie eu sit amet massa. Ut sagittis pulvinar auctor. Vivamus sit amet libero viverra risus tempus lobortis. Sed sagittis, urna quis rutrum vehicula, lorem quam scelerisque libero, et mollis justo lorem et lectus. Quisque lacinia velit nec finibus volutpat. Phasellus sit amet laoreet mi, eu accumsan lorem.

Praesent tincidunt tristique arcu vel rhoncus. Maecenas dignissim tristique pretium. Duis lacinia sit amet ante in semper. Aliquam non efficitur massa. Nam laoreet turpis pharetra quam porttitor, a lacinia mauris mollis. Aliquam sit amet metus efficitur, porta diam id, sagittis dolor. Nulla suscipit scelerisque nisi, vitae cursus massa tempus id. Cras a mi dictum, auctor leo et, vestibulum mauris. Nam at vehicula ante. Maecenas faucibus mattis congue. Etiam euismod, lectus quis mattis mollis, ante odio euismod ex, et scelerisque neque neque eget tortor. Nulla ultricies mi sed augue faucibus, in mattis libero tristique. Nullam id condimentum nunc.

Etiam id sapien luctus, mollis sapien ut, suscipit leo. Fusce blandit blandit diam non sollicitudin. Praesent varius nisi vitae semper placerat. Praesent et mauris id ex commodo aliquam non quis nisi. Pellentesque interdum, orci non sollicitudin efficitur, purus turpis efficitur lectus, eu tempus nisl mauris vitae mauris. Nunc vel dapibus velit. Donec bibendum nibh quis odio commodo dapibus. Fusce et felis vel magna tincidunt varius. Quisque ullamcorper porta porttitor. Morbi at condimentum leo, sit amet pellentesque quam. Ut vulputate purus nulla, a ultrices justo scelerisque vitae. Nullam egestas nunc at diam consequat condimentum. Nulla tincidunt libero ullamcorper velit auctor ornare.

Proin accumsan purus massa, id imperdiet mauris finibus id. Phasellus rutrum dictum varius. Proin ut malesuada justo. Ut sit amet neque leo. Proin mauris augue, gravida ac risus ut, maximus pharetra sapien. Vestibulum a commodo massa. Nulla sed sapien vel nulla egestas laoreet sit amet et urna. Sed blandit pharetra lorem non viverra. Cras vestibulum libero nibh, vitae scelerisque mauris facilisis sit amet. Morbi tristique at purus vitae facilisis.

Donec ut metus quis velit pretium gravida. Maecenas lobortis, orci vitae tempor consectetur, diam turpis efficitur purus, vitae tincidunt ex metus vel dolor. Fusce aliquam diam lacinia est fringilla convallis. Morbi efficitur condimentum pharetra. Curabitur porttitor convallis sodales. Ut a mi commodo, ultrices nunc non, convallis erat. Nulla facilisi. Nunc facilisis sem est, et posuere justo sagittis sit amet. Duis eget vulputate turpis, sit amet mattis nibh. Ut metus augue, ultrices a arcu sit amet, pharetra varius felis. Aenean maximus, neque id elementum posuere, urna turpis volutpat orci, eu euismod magna massa at nibh. Nulla id erat ligula. Ut viverra, tortor rutrum commodo aliquet, ligula erat lacinia tellus, eget sodales ligula sem at ligula. Vivamus sit amet magna auctor, aliquet odio vitae, feugiat massa. Vestibulum malesuada viverra urna, vitae imperdiet tellus lobortis vitae. Quisque sed sapien quis orci ultrices feugiat quis elementum quam.

Sed tortor augue, vehicula sit amet malesuada quis, dictum sed risus. Morbi ac leo et velit aliquam molestie. Duis semper convallis efficitur. Nullam pellentesque orci ut nisl fringilla tincidunt pretium aliquam dolor. Proin nec libero nisi. Integer nec ante arcu. In vestibulum venenatis tortor vel fermentum.

In sit amet sagittis augue. Aenean tempus lorem orci. Curabitur id consequat urna, in pharetra odio. Fusce quam nisi, commodo sed ex id, elementum efficitur lacus. Nullam turpis magna, vulputate at ipsum sit amet, tempor sagittis odio. Nulla quis venenatis libero. In auctor luctus ullamcorper. Suspendisse felis tortor, dignissim vitae pharetra quis, consectetur quis risus.

Curabitur eget metus nec diam tristique mollis id rhoncus massa. Suspendisse potenti. Etiam laoreet at metus sit amet pulvinar. Fusce dictum nisl vitae turpis lobortis, eu consequat nibh tempus. Phasellus quis ultrices orci. Nunc vulputate ultrices velit nec bibendum. Suspendisse ut elit facilisis, eleifend orci sed, consectetur nisl. Sed feugiat ut nisl vel ornare. Vestibulum at mauris mollis, sollicitudin neque eget, lobortis ante. Maecenas molestie ultrices urna, pretium suscipit purus fringilla quis. Sed risus dolor, malesuada a nulla ac, commodo volutpat mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque laoreet laoreet purus, sit amet lacinia libero porttitor at. Nunc sed tincidunt ante. Sed commodo, lectus et sodales pretium, neque velit viverra sem, id lacinia mauris diam sit amet metus. Donec non ligula eu neque blandit congue.

Cras suscipit varius nunc. Duis et accumsan lorem, in egestas augue. Mauris posuere luctus arcu ut pretium. Donec porta tellus quam, ut rutrum nibh mollis ut. Aenean mauris tortor, blandit at nunc ultrices, efficitur varius eros. Proin pretium magna sed leo luctus, vel feugiat magna accumsan. Fusce porttitor massa quis lorem tincidunt, eu molestie leo semper. In placerat, massa ac consectetur fermentum, nibh nunc eleifend tellus, eget ultrices augue tellus ut libero. Mauris sollicitudin porttitor pellentesque. Pellentesque nec maximus dolor. Nunc at gravida sem, sodales bibendum sem. Nulla quis nunc ante.

Phasellus gravida nibh erat, ac ullamcorper ante sodales quis. Sed a pellentesque magna, in faucibus magna. Nulla cursus hendrerit quam, sit amet facilisis lectus accumsan et. Phasellus tristique, nisi quis semper porttitor, magna lorem sodales dolor, sed venenatis mi libero quis velit. Sed tincidunt tellus nec neque scelerisque eleifend. Pellentesque non ex eget justo dictum tincidunt. Curabitur vestibulum justo a urna commodo, fringilla accumsan tellus efficitur. Suspendisse eu nibh ac elit finibus dapibus vel nec quam. Integer vulputate maximus congue. Nunc nisi lectus, molestie ac gravida mollis, sollicitudin a diam. Fusce lobortis, erat ut posuere posuere, sem risus placerat lectus, eget semper sapien magna a orci. Sed eget justo ex. Vivamus efficitur purus ex, quis efficitur erat maximus ac. Phasellus dapibus nisi sit amet mi blandit laoreet. Nam at consectetur nisi, elementum commodo libero. Donec lacus velit, ornare rutrum sodales id, porta ut quam.

Vestibulum bibendum gravida libero, vel sodales purus ultrices ullamcorper. Nunc vel purus accumsan, laoreet justo semper, hendrerit est. Duis ut urna a nibh volutpat bibendum sed nec lectus. In non massa lorem. Maecenas a mauris venenatis, finibus dolor in, accumsan sapien. Sed facilisis consectetur mauris, id eleifend dui dapibus auctor. Donec fermentum imperdiet consectetur. Nam at hendrerit nisi. Quisque consequat consectetur fermentum. Maecenas aliquet accumsan tincidunt. Nullam lacinia nisl sapien, in efficitur nisi porttitor at. Maecenas non hendrerit dolor, quis egestas sem. Nulla interdum scelerisque urna, eu maximus eros mollis a. Donec semper urna at metus luctus, vel euismod lorem faucibus.

Nulla accumsan mattis nibh, sit amet efficitur augue lacinia a. Maecenas mattis, urna in tincidunt dignissim, eros enim elementum augue, vel lobortis augue nibh quis augue. Ut ornare, mauris ac porttitor pellentesque, quam velit scelerisque arcu, vestibulum venenatis tortor ex in nulla. Duis interdum cursus viverra. Quisque eu eleifend mi. Quisque sagittis rhoncus consequat. Nulla facilisi. Donec fringilla nec mi id pellentesque. Praesent neque ligula, luctus eu urna ut, tempus posuere libero. Duis blandit, leo at tincidunt feugiat, lorem tellus venenatis libero, ac finibus risus purus ut diam. Maecenas justo ante, aliquam eu laoreet non, ultricies sit amet eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi nec gravida mauris, non faucibus nisl.

Sed ullamcorper tincidunt felis at egestas. Praesent diam lacus, malesuada id ipsum in, luctus pharetra mauris. Vivamus vulputate molestie orci, at lacinia elit gravida accumsan. Cras vel nisi sit amet erat finibus auctor et sed nulla. Nullam congue pretium orci, sed auctor massa vestibulum vel. Phasellus porta ipsum vel nisi semper, condimentum finibus urna pretium. Aenean in fermentum magna. Pellentesque venenatis suscipit eros a molestie. Aenean id nulla eu metus aliquam facilisis. Nullam tincidunt elit nec ipsum tristique, eu molestie nisl volutpat. Phasellus dictum lectus egestas orci gravida ornare. Praesent blandit, dui tempor commodo commodo, diam lacus aliquet lacus, eget rutrum diam urna sed tellus. Suspendisse vitae tempor erat. Ut malesuada massa nec arcu ultrices mattis.";

            var sw = Stopwatch.StartNew();

            Console.WriteLine(VowelsCount.FindSubstring(text,20));

            sw.Stop();
            Console.WriteLine(sw.ElapsedMilliseconds);

        }
    }
}
